const streetNames = [
  "Ace Jones Drive",
  "Adam's Apple Boulevard",
  "Aguja Street",
  "Alta Place",
  "Amarillo Vista",
  "Amarillo Way",
  "Americano Way",
  "Bay City Avenue",
  "Baytree Canyon Road",
  "Boulevard Del Perro",
  "Bridge Street",
  "Caesars Place",
  "Calais Avenue",
  "Capital Boulevard",
  "Carcer Way",
  "Carson Avenue",
  "Chum Street",
  "Clinton Avenue",
  "Cockingend Drive",
  "Conquistador Street",
  "Cortes Street",
  "Cougar Avenue",
  "Crusade Road",
  "Davis Avenue",
  "Didion Drive",
  "Dorset Drive",
  "Dorset Place",
  "Dunstable Drive",
  "Dutch London Street",
  "Eastbourne Way",
  "East Galileo Avenue",
  "East Mirror Drive",
  "Elgin Avenue",
  "Equality Way",
  "Exceptionalists Way",
  "Fantastic Place",
  "Fenwell Place",
  "Forum Drive",
  "Galileo Road",
  "Ginger Street",
  "Glory Way",
  "Goma Street",
  "Greenwich Parkway",
  "Greenwich Way",
  "Grove Street",
  "Hangman Avenue",
  "Harlow Drive",
  "Hawick Avenue",
  "Heritage Way",
  "Ineseno Road",
  "Invention Court",
  "Innovation Way",
  "Jamestown Street",
  "Jousting Way",
  "Kimble Hill Drive",
  "Kortz Drive",
  "La Puerta Freeway",
  "Lake Vinewood Drive",
  "Las Lagunas Boulevard",
  "Los Santos Freeway",
  "Low Power Street",
  "Macdonald Street",
  "Mad Wayne Thunder Drive",
  "Marathon Avenue",
  "Marlowe Drive",
  "Milton Road",
  "Mirror Park Boulevard",
  "Morningwood Boulevard",
  "Mount Haan Drive",
  "Nikola Place",
  "Normandy Drive",
  "North Archer Avenue",
  "North Conker Avenue",
  "North Sheldon Avenue",
  "Occupation Avenue",
  "Orchardville Avenue",
  "Palomino Avenue",
  "Peaceful Street",
  "Perth Street",
  "Picture Perfect Drive",
  "Plaice Place",
  "Playa Vista",
  "Popular Street",
  "Portola Drive",
  "Power Street",
  "Prosperity Street",
  "Prosperity Street Promenade",
  "Red Desert Avenue",
  "Richman Street",
  "Rockford Drive",
  "Roy Lowenstein Boulevard",
  "Rub Street",
  "San Andreas Avenue",
  "San Vitus Boulevard",
  "Senora Road",
  "Shank Street",
  "Signal Street",
  "Sinners Passage",
  "South Boulevard Del Perro",
  "South Mo Milton Drive",
  "South Rockford Drive",
  "South Shambles Street",
  "Spanish Avenue",
  "Steele Way",
  "Strangeways Drive",
  "Strawberry Avenue",
  "Supply Street",
  "Sustancia Road",
  "Swiss Street",
  "Tackle Street",
  "Tangerine Street",
  "Tongva Drive",
  "Tower Way",
  "Tug Street",
  "Utopia Gardens",
  "Vespucci Boulevard",
  "Vinewood Boulevard",
  "Vine Drive",
  "Vitus Street",
  "Voodoo Place",
  "West Eclipse Boulevard",
  "West Mirror Drive",
  "Whispymound Drive",
  "Wild Oats Drive",
  "York Street",
  "Zancudo Avenue",
  "Zancudo Barranca",
  "Zancudo Road",
];

export default streetNames;
